---
# web servers handlers file

- name: start apache2
  service: name=apache2 state=started

- name: stop httpd
  service: name=apache2 state=stopped

- name: restart apache2
  service: name=apache2 state=restarted